credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              description: "githubuserssh"
              id: "githubuserssh"
              privateKeySource:
                directEntry:
                  privateKey: "{AQAAABAAAAywWhxR+PlGBvAlMf/zAkHrBailh55HAEE4oocDT3Lxq73hzA5RBHdnGwVYDBOg9M3JmhGAmYMOEzeJ+FLpsZe+aaEytcz6ICYPf0P0LKdXOL1uTIfq1zsGX3tBt8M1XWoYjPVS6upjvwzY5fa9NfEpCoDn+xIyJSRGb9BByFHIpuL8OP1bKlJHB2UfZVm05l81tcLi2O7RxU+7tFIkQyRMVos3pMuF+Y5ufkoNzfSUNTxU4sWO/IaLuBhihTcBbsz9SIsX7/1Gom9680XXwLjq4No750BG70FjHnSCTQJ0J1ovvxgqcxpbgs0P2bBNwEInv9ljnSoNwwcn7XgNi8YByhZCG40tqwIGvoUcHGpyMITDW/KVwthGY6W3mDa1NypdEti3/HjtWVzRmwaK3DKMbtS37Qgybxz+EwpZtA6Sxw33S7uYFWKj8x24Sihvhu3tSMySHixK1kgC6PkO3Qv7W/jwyQv6jWPhp/EZEPwJFKuD468ukNxnqeUky+n9Tku+M22pDE1eIFDrYKxegm1UFkXq6U1SJ0nc9ljl0H7sUBBwOMmjxpiI0h0WcC9NNOyT3BA2fF5r2JgrGalgJdVK3GpeCgto8dp3ExoAjftqcUCU8rG1T1WILfG9MjBLI7JD8SzOhxUz5uTcUZKRKMlzIoWM7QVwEuZY4NJvF3vlxMkN4flQ95O/7Pyqm84Q6gvy9WjCbcIPUCLWH8qPxQH8TcoPG36yuGqxV/ArVT/gisKmCzEcN6sYP6lXnv3yzNXuu4EV89sQea1dduxqC6Mla8eukw5nxy7FY6ttz4QI3Dj7/wlE1paJ9cFuhikVK0jBc/64Faa4rZqywFldr+poqtcnEBobNPBV2Fs82nUpSS+mbjSyXJIVsMQH0838YL9MVHAqBNuNrsKFRHQKC6PzfoYqrpiTugaUF3Ff2AUcqIYjkSE8zJY8QqfD4nGUgpgkUdjzMq1kDmPvrw7aLq1Q68tBHdspMJKwlhJgOUowrJvpn5qTdJ4QDJQ686D1gHJkaPtxdjdH397HWzC5WY7P0svSYHdmuYFd3AHqYukrThy4a3CLHh+HxqrUO5BYeSj/ZJ8WjVdXnahESY65L1F6dVEP5Hn/ImKvZw1bBwSKgGxPDfuaXeTuZVzIyuo5oEUgfyKGPQzIFSuQYVhnXa9ad+z5ZBik6S/uEa1lzMBTgM3wwwbMtvNwfZtUHj6mztmBJ4XtEdIqvCaNU4XOQwVPpyZ6F2Z3IQDvch/rVojzaSLeBn/gm/gzHQ3VdIsIsigTQn2jr0RTQNGfvTuzqbn9viTEMPabtwrGcjOLRGxh4EJ7TXTwP1e9l+kCwGdomd+Usvhs7Gx3id8zt4gMjNp19CqJ0UoFEXVLBPttn/aX5WvX0rBIEF64Si9k8NXefLpNlWhTYBXx9uUmH5LD5eH1PE9T/X5fEhzD2f6/ZQPlZl3K2hBqGjxvRpPezBVZckdk4rvC1/3IK/OzpVo5eUeqJ0aJmKHXaBRLEwg5JJzGPVUbUXVSfJWjLcWViB7ht65nEFVSAa+IKaWVQ1nCF8WRG64K2M5ndkgXVfXC9DuRJ9RtDPfXye80R1L05+IbvyKVmcnmrvtQ32ssvk0716IIQ5ftBvdKe0brKFGD9ZEK/nZ/mt+svk5MXVBPsWkWSENAoUS1v/jcs4xQkiK9W+mU45Wj8lGR3vGsf+SGnCH9WSa9KhVUxMWj365RoIb6MSrX9QnUqZufuwrgzJ0Fqt+09o/xIrCPmeTa1VWmuwC8GnC0A4Rt6zgNc4LUTIZpilWo4zziRdhR3WIKuokGqJhxff3J2M4c206SvYmiSvBONBXBqt3AlCtUtzudelBjz/Yp6qzwBptghd8WUVs1fxIEep4mA2iNrsbvzqwSPXwlSCy4g8FHsm4TyJEZ+4y1ELUPgVbT/kaADDczRQ4mlC+Skc16Zbu3j6KibSJ4oqEIPkH1B0ncNspeCGuXkjpU3mulUcVwM69sRwWtb7MwmWVNQWa1iNGBBD/nPAT9W2ptA49iFzyTjQ9ajxw+7vh1nBgNe002QbuE1Ylf8ElnbYI6T8BNMuyFVlyr1o3fiRk82Nr0NtZtcyCiOtYTS7uedp/WLZ0pUUj7lEw5vq2B++3DbcDdLvNeWadY/qY9IQhbbZ0kFEGjc3QQ+awh7fGLbbNNVFS13cDibafISxAOjHDG/7RKCJJvnq+SCtkwin0QBTdMrYb4qv62oQr+g3BayqODjE2D7AhvTuJmRBaGf/Z8H2/UcaSPdd3AaiztAOdw5VcvcWr3lCidZk+pNdFXy9QVjgMurBT2kYOs3ZBzWB68xum+H00+8E3FOX8jEdo3RUwEUcjTA+RZMSOV0WxPFQC+gdpwnLQHbif8nmqZ2lXZz+a3++bWae/PYhQup3302anis+IYyA882TKZLjyary6Wvh5ivijFi6MdrV2AH5lrXNrMH52vEzn6vO7+PZuA1Iwxf8635uMNutRhdWOpnkhjlQqnLRRr0z5gAmyYtQAYDL7NDZkVgwK5OWYZE+gKuMkexCDLGf4jq5R/wMRAYaE3YXCeoXaKHbDR4LkL2gf34WL9N79UzWm5QdHbh+xZUQFfqi9TjmsGB822dmwwPapJ2vmvzqsm6ggyXWmdaylbOWyfQNtOdEU0pTw1CI70G0W7SvDC2vNt+jB++sNXIKoYqZ5wdpDF8tjMyzMlbw1jDN94Vqva+LhsQfDDgSwJUuhe5tMU4GL0aDwTuMBpgTuFG+J7GV1RwjrO8DSHUDjloTqBnMg67Y2aUAgEEa7DEW78WAdO/JbZ5ChJiBKiKKvccOXAQyxBKN16Z87J97ecDCWInWxX78SBQX/addU3CagM2yGhCJxKKWyUKGb8hefDzl/ofpNJwKeZ0Wp7PRChKVHC4KpAc4WpfW/3TddYmWt9jsHoFUZn6wUiMKp+879UOpuIWBICPkH39f1y6tD7L6c0s+KF5cblswYoP9W2bYoB/FLGjCZd/41Z9cfqxQprGGsrh8ynr2m/GPGl2GcNfH4Yr2BX+Cr+DkeInm6mBtm7/SkeB1I2hRK28h2S7ezups87NqwRCnyCOkGFIiEVS6TgrV163KzjovztvcQ3uQJ9bpdJV+dHH80vCenk4wVdRRjm2GCkZ2c7AqM4F42IaiZQIc3jv8AsUPVRgUtssHf6iAR+UpJPs732nfSfo29YJoZVRRZLNfrcoaG0ijR1xsErH8hh/0k1W6mEGBssW0a3wHpyqe8ybAyg3tHRgYlzcLLSHxM9jVBJxTVl7iwK85M21HuR8GUelHRym9X9kQjkt9M90B5y+19qpHqgh7k7jWPHhPsJ8uiEuqRHYVCJwzdQNyRmde5mQ0F8/KlqLEq1mYgyi1whdk3ZEnLFkw94f/ODCTB8CS+tEKA/9OZd+BEKn1ccRKsSascvzA0c/JdBwBrOb/EpnEANbkeO9QjJ2C9NFN+zjqbwFAuy3qLPlD9CQNRasNjUZ4MCwLjW1fEqGCQUdvkdMUxPRwvU66pRBZYSve0kdhY5jqEg2uvBnSOHH0i2o8d+pQYG1yGwnxXhCpYh4bALRrWBMisMbvxrJwKXpIVsK4X7A0jmPlAIu3ARNOz5vjKE7cBLl7XgM4VrVykiHhpYywPJ0Ff51Zs3XiMsjNzQYgg+Esz1O1OcTmxCwVb0iKGqs42t3m7S5a7B7uAC2ok8pSZEy28Egk3123XMPtOerq2fxFYnbXx1vZAEq1bZulZjlOcncg2r6xn7LPULQKNCS1EV3tm6gyPnA1fbiXBFL7hgrMU0dpz0GXScFostx4cPgSU08wm4c6GJOZtZ40GZQaugfRGkfZReXUAyBwssTB9mbdUkjDGdzKtN8GvUuqcMjkCzh8KGLU2KmABGyS34HFUKBqc4Gn59ungfuiL7QGSQhhtJwKff2vmzrS6B4Ys7q57tBUuKwq3Az+IgQlDaNJQVkZXgYqBSkkfRplnJyyIKHV5OLKn0qSR4ADOTXAl31VjNBGvMdGVrdJfgd/ewR2F8fvHXz8vPnMKhjsEsMkG7Vm0PHJgnHJ+gVUNELV5H4roMSS+s3OWLwGsApd4A5DWgL8U4lMbpk6CAhSLNF9wGMgsLALJD9lLUZyAQNa9gk5s+PNr92L0vJ9B1IicpvkpdhlVu6rsCQdhZgKglS6L4Kns9+pCPhVb4gnr8nfCzwGjgxwEAkqlhOmUNImSXdEKtEb2jyajLOQnoLNmc7KgXiyXaB9BEEHPnn7/koFE8+L+rvmPPbXsVYnhM0newuglgW8x9I8NxxrpsU/rm9OzuP6RfOGPCI3nbNMNwrA1tasl0LhLgb7ig83z26aMF5m7WXp/JNFpo}"
              scope: GLOBAL
              username: "cccaternberg"
          - usernamePassword:
              description: "githubuserpw"
              id: "githubuserpw"
              password: "{AQAAABAAAAAQX8+uCTW7KF8xUlKdX28VGqVv1OozOnIK571sbqas3RQ=}"
              scope: GLOBAL
              username: "cccaternberg"
          - usernamePassword:
              description: "githubuseraccesstoken"
              id: "githubuseraccesstoken"
              password: "{AQAAABAAAAAwPkyO9hMgbJc0h4BFHJgW+YwIXVwjmYdC3agvzuoCMKnnGgevWQXTmzfi9VFq0skaYsS8dKB+Z5ooSTnlqKOwaQ==}"
              scope: GLOBAL
              username: "cccaternberg"
          - string:
              description: "githubaccesstoken"
              id: "githubaccesstoken"
              scope: GLOBAL
              secret: "{AQAAABAAAAAwipg8KdyRmb8PtI3zA7Edksm/sKS/cLQ/6fqfydMLRA0fjTHqB71mVRP3HlV+xLqhFhSPKqRx14HK2s2XKE7+1w==}"

jenkins:
  systemMessage: "Jenkins configured using CasC v.84 - master0"
  numExecutors: 0
  mode: NORMAL
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  securityRealm: "operationsCenter"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "cap-core-mm"
        url: "https://jenkins-updates.cloudbees.com/update-center/envelope-core-mm/update-center.json"
      - id: "core-mm-offline"
        url: "file:/tmp/jenkins/war/WEB-INF/plugins/update-center.json"
  myViewsTabBar: "standard"
  primaryView:
    all:
      name: "all"
  projectNamingStrategy:
    pattern:
      description: "My naming strategy"
      forceExistingJobs: false
      namePattern: ".*"
jobs:
  - script: |
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }

      organizationFolder('GH-jenkinsci') {
          description('This contains branch source jobs for GH-jenkinsci GitHub')
          displayName('GH-jenkinsci')
          triggers {
            periodic(2400)
          }
          organizations {
            github {
              repoOwner("cccaternberg")
              apiUri("https://api.github.com")
              credentialsId('githubaccesstoken')
              traits {
                publicRepoPullRequestFilterTrait()
              }
            }
          }

          projectFactories {
            workflowMultiBranchProjectFactory {
              // Relative location within the checkout of your Pipeline script.
              scriptPath("Jenkinsfile")
            }
          }
        }
beekeeper:
  enabled: true
  securityWarnings:
    enabledForCore: true
    enabledForPlugins: true
  upgrades:
    autoDowngradePlugins: false
    autoUpgradePlugins: false
notificationConfiguration:
  enabled: false
kube:
  podTemplatesConfiguration:
    templates:
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "maven:3.3.9-jdk-8-alpine"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "maven"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "appropriate/curl"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "curl"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "gradle"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "gradle"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "lachlanevenson/k8s-kubectl:latest"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "kubectl"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "lachlanevenson/k8s-helm:latest"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "helm"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        instanceCap: 10
        instanceCapStr: "10"
        label: "cloudbees-core"
        name: "cloudbees-core"
        slaveConnectTimeout: 10000
        slaveConnectTimeoutStr: "10000"
        volumes:
          - persistentVolumeClaim:
              claimName: "maven-repo"
              mountPath: "/tmp/cache"
              readOnly: false
        yamlMergeStrategy: "override"
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "maven:3.3.9-jdk-8-alpine"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "maven"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        label: "cb-core-maven"
        name: "cb-core-maven"
        nodeUsageMode: NORMAL
        volumes:
          - hostPathVolume:
              hostPath: "/var/run/docker.sock"
              mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "benhall/dind-jenkins-agent"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "dind"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        name: "dind-podtemplate"
        volumes:
          - hostPathVolume:
              hostPath: "/var/run/docker.sock"
              mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
security:
  anonymizeSupportBundle:
    enabled: false
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
#  globalJobDslSecurityConfiguration:
#    useScriptSecurity: true
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
      - "method com.cloudbees.jenkins.plugins.sshcredentials.SSHUserPrivateKey getPrivateKey"
      - "method com.cloudbees.plugins.credentials.common.IdCredentials getId"
      - "method com.cloudbees.plugins.credentials.common.PasswordCredentials getPassword"
      - "method com.cloudbees.plugins.credentials.common.UsernameCredentials getUsername"
      - "method hudson.model.ItemGroup getAllItems java.lang.Class"
      - "method hudson.model.Job getLastBuild"
      - "method org.apache.maven.model.Model getGroupId"
      - "new com.cwctravel.hudson.plugins.extended_choice_parameter.ExtendedChoiceParameterDefinition\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String boolean boolean int java.lang.String java.lang.String"
      - "staticMethod com.cloudbees.plugins.credentials.CredentialsProvider lookupCredentials\
      \ java.lang.Class hudson.model.ItemGroup org.acegisecurity.Authentication java.util.List"

