jenkins:
  systemMessage: "Jenkins configured using CasC v.144 - ${MASTER_DOMAIN}"
  agentProtocols:
    - "Diagnostic-Ping"
    - "JNLP4-connect"
    - "OperationsCenter2"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
    - name: "cb-core-maven"
    - name: "cloudbees-core"
    - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  projectNamingStrategy:
    pattern:
      description: "My naming strategy"
      forceExistingJobs: false
      namePattern: ".*"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm: "operationsCenter"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "virtual-cap-core-mm"
        url: "https://jenkins-updates.cloudbees.com/update-center/envelope-core-mm/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
jobs:
  - script: |
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }

      organizationFolder('GH-jenkinsci') {
          description('This contains branch source jobs for GH-jenkinsci GitHub')
          displayName('GH-jenkinsci')
          triggers {
            periodic(2400)
          }
          organizations {
            github {
              repoOwner("cccaternberg")
              apiUri("https://api.github.com")
              credentialsId('github-accesstoken')
              traits {
                publicRepoPullRequestFilterTrait()
              }
            }
          }

          projectFactories {
            workflowMultiBranchProjectFactory {
              // Relative location within the checkout of your Pipeline script.
              scriptPath("Jenkinsfile")
            }
          }
        }
cloudbees-monitoring:
  conditionList:
    - individualHealthCheck:
        alertAfter: "5sec"
        name: "health check"
        recipientList:
          - email:
              emailAddresses: "acaternberg@cloudbees.com"
              subjectPrefix: "[Jenkins Alert]"
beekeeper:
  enabled: true
  securityWarnings:
    enabledForCore: true
    enabledForPlugins: true
  upgrades:
    autoDowngradePlugins: false
    autoUpgradePlugins: false
notificationConfiguration:
  enabled: false
security:
  anonymizeSupportBundle:
    enabled: false
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
      - "method com.cloudbees.jenkins.plugins.sshcredentials.SSHUserPrivateKey getPrivateKey"
      - "method com.cloudbees.plugins.credentials.common.IdCredentials getId"
      - "method com.cloudbees.plugins.credentials.common.PasswordCredentials getPassword"
      - "method com.cloudbees.plugins.credentials.common.UsernameCredentials getUsername"
      - "method hudson.model.ItemGroup getAllItems java.lang.Class"
      - "method hudson.model.Job getLastBuild"
      - "method org.apache.maven.model.Model getGroupId"
      - "new com.cwctravel.hudson.plugins.extended_choice_parameter.ExtendedChoiceParameterDefinition\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String boolean boolean int java.lang.String java.lang.String"
      - "staticMethod com.cloudbees.plugins.credentials.CredentialsProvider lookupCredentials\
      \ java.lang.Class hudson.model.ItemGroup org.acegisecurity.Authentication java.util.List"
unclassified:
  alerter:
    conditionList:
      - individualHealthCheck:
          alertAfter: "5sec"
          name: "health check"
          recipientList:
            - email:
                emailAddresses: "acaternberg@cloudbees.com"
                subjectPrefix: "[Jenkins Alert]"
  ansiColorBuildWrapper:
    colorMaps:
      - black: "#000000"
        blackB: "#4C4C4C"
        blue: "#1E90FF"
        blueB: "#4682B4"
        cyan: "#00CDCD"
        cyanB: "#00FFFF"
        green: "#00CD00"
        greenB: "#00FF00"
        magenta: "#CD00CD"
        magentaB: "#FF00FF"
        name: "xterm"
        red: "#CD0000"
        redB: "#FF0000"
        white: "#E5E5E5"
        whiteB: "#FFFFFF"
        yellow: "#CDCD00"
        yellowB: "#FFFF00"
      - black: "#000000"
        blackB: "#555555"
        blue: "#0000AA"
        blueB: "#5555FF"
        cyan: "#00AAAA"
        cyanB: "#55FFFF"
        defaultBackground: 0
        defaultForeground: 7
        green: "#00AA00"
        greenB: "#55FF55"
        magenta: "#AA00AA"
        magentaB: "#FF55FF"
        name: "vga"
        red: "#AA0000"
        redB: "#FF5555"
        white: "#AAAAAA"
        whiteB: "#FFFFFF"
        yellow: "#AA5500"
        yellowB: "#FFFF55"
      - black: "black"
        blackB: "black"
        blue: "blue"
        blueB: "blue"
        cyan: "cyan"
        cyanB: "cyan"
        green: "green"
        greenB: "green"
        magenta: "magenta"
        magentaB: "magenta"
        name: "css"
        red: "red"
        redB: "red"
        white: "white"
        whiteB: "white"
        yellow: "yellow"
        yellowB: "yellow"
      - black: "#2E3436"
        blackB: "#2E3436"
        blue: "#3465A4"
        blueB: "#3465A4"
        cyan: "#06989A"
        cyanB: "#06989A"
        defaultBackground: 0
        defaultForeground: 7
        green: "#4E9A06"
        greenB: "#4E9A06"
        magenta: "#75507B"
        magentaB: "#75507B"
        name: "gnome-terminal"
        red: "#CC0000"
        redB: "#CC0000"
        white: "#D3D7CF"
        whiteB: "#D3D7CF"
        yellow: "#C4A000"
        yellowB: "#C4A000"
  artifactManager:
    artifactManagerFactories:
      - "jSync"
  artifactoryBuilder:
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        ignoreCredentialPluginDisabled: true
        overridingCredentials: false
        password: "{AQAAABAAAAAQGj2K9LC6b4aG7PKev4UKyL28qfit1+WC/cvLTAM2Tys=}"
        username: "****"
      timeout: 300
    useCredentialsPlugin: false
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketCloudEndpoint:
          enableCache: false
          manageHooks: false
          repositoriesCacheDuration: 0
          teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  cloudbeesPlatform:
    server:
      apiUrl: "https://flow-server.cloudbees-core:8443/"
      ignoreSslConnectionErrors: true
    url: "https://sda.meckermail.de/"
  defaultFolderConfiguration:
    healthMetrics:
      - jobStatusHealthMetric:
          countVirginJobs: false
          failure: true
          success: true
          unbuilt: true
          unstable: true
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpPassword: "{AQAAABAAAAAQO/3oDJYbr4OjQbCZk4Vnb9n/CbqxfIc8QElrxyVj6G4=}"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  experimentalPlugins:
    enabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "https://sda.meckermail.de/${MASTER_DOMAIN}/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalNexusConfiguration:
    instanceId: "92096b7097d844359862c708e6812108"
    nxrmConfigs:
      - nxrm3Configuration:
          displayName: "mynexus"
          id: "nexus"
          internalId: "6a31d43f-3033-4419-affe-b9566836fe47"
          serverUrl: "http://nexus.34.98.108.14.nip.io/"
  hashicorpVault:
    configuration:
      engineVersion: 2
      timeout: 60
  hibernationConfiguration:
    activities:
      - "build"
      - "web"
    enabled: false
    gracePeriod: 120
  ivyBuildTrigger:
    extendedVersionMatching: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://sda.meckermail.de/${MASTER_DOMAIN}/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  usageStatisticsCloudBees:
    usageStatisticsCollected: true
tool:
  cloudbeesPluginUsageAnalyzer:
    enabled: true
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"