credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              description: "githubuserssh"
              id: "githubuserssh"
              privateKeySource:
                directEntry:
                  privateKey: "{AQAAABAAAAywPjGjfVIQPPCoEFea/m4XamgRYsaM070IvRlU2yIOIIxrU7YZRjffUpTmzrk1GSGDUHT4WDUSHccJbegULKkz/J67PIL6qqnSWnK36+hSxxHaywQTMg4s+0dpOc86zhAmOnDFpuJGgpR8yWRNs46Yaq0O07Hy46BddtSHe46N+m8o6EI1zCtnUHCKNkeE1csoXZmQb0RuwMwNo8qQc6XudD1fD4SmHTvM37eozNSCOtoQV/k/Xz1IAeZaMmo9rhPFNa4VWuWjcnIq1F5PIaYxPNeSWpz97eoGQ1/BgIAf5SF7N+yLGwzNGrKK3vZo2I7f6bAUPcyiATRghYmbFYDjxsKMw7tP/XB8sjYrZhO/J0RX+7xXfTkMcm5iLbV9GReS9CCvvWsBa8/QR+5W4abLUVNk6R1iX4ZnBITD0SC+dvw9OvlGf0JTWvLUrDygok8f/J1fV85x9D6s+55Cbmrl408F4eRik0Mj24a8tpRK84ll97Lw2AXR0+BV90tj/bgJXLIG/lAy3rzorDlBKRoF3ru/jD8Rdco5pvuR7iRDIwaFMR+SpiPJhElILnyHTQFOTUUPzFsYeXbJKF4+DmfueG4gSwyK7iGIvjtYcJIr5aiqN1CpPGFiB79ZmzNSWElpf2U7mIkqaGG7cVdWp6+1i3VEDCUGVIvAdh6BmI9rFjn5sL+7LaV/DXhwLZdplt020oHy80iIboNlrtyUIDDCylD58wXb5SQp6/Kt51k2I1djEMSc86kXBQoEB6fPZadIk67iexphQxKhrpy0suO6wZItZ6XoyZthkFEJH3DV9L8nycUpwWQIZs0HHULcbbnVcGxJQeuEeWD06AWT8gEhWVNHFe0jLrcT2uzsa5awctFXH6IdnEteuG1dRxMxkwLPtqbotm7Ql3duBXG2QcZ9XlFLnWXhRkt8/wNDYUwETcSktY+pNrQGJsOjjrfkozSyqmiM6NL9y+mj6ftx/a36ea9VHmOzkWES8JsKJuJ2/pPTYnwuvqujNEK6a5jHahqW2XlM0W5Tmk4lFl68SHr6bb4ZwRAKyjoF3WOwQEDOi74lgNiOkqFASk2aE5/atZjEa0qYh5k7Lv8dCen0MiaHVXiKREawwnXGDvNo6NMrke1FiZMeZi9JHSnz8A6//97CWF6umumr7m3yk8ZO/a2lmTGzZe0W9yCrcFzlcS9WHo0u+Az5zieLlXpC0WHKLn35Tb4fFHb9aQqeT3yQ0QeP/afZW5uyuVXtahuQ8x/g8pW2/UjSScNKbj7vnAl1KoDkHXbJkiMk24i58z6JOVuwjbA9yeMEGryTKXwXE3lI+9Gu8p9av1rssuZA4NRO/KJgwOfx+xExkG7vLJWE77ermK6NWaL0yFJ3i2LiWgYw1UsJQWWwVEMa2J//6Y0OYMDZ+LbRBGdG/XEyR9qpvGPgAw3z/l6KvWZs+tBgo1MhPFQ0ltuw0sChXPxplbtXk6STWZmZH7e/jBGIV0oxTMHdGgIp9IzqJW0X35wZjDdqWiY3uvF31imdn1aXnPMjyPGIWzA8AmMJ4v3+P/6YJW0mvKsR4VD9jBzlWkK2y0XPTOc1Xt688XL1kBZVSlhj6MyJ+TwUhS/DNmvaoZ4IlZLsNX17xfzpKQqn6dbC+COs9yJYPBNrS/7NZOZZL2un1gxb5SrUR4F9boSQmLZu6PNJYLylqv+zCfjD71qOHot00qOCPGqAoN15PSWOqv/AFige44zC2brNXUeqPrYRs4FXVgNWzOCjcygkqtAaFRLhU5018b27MXAZKjChyiPdn0cAVfczw/H/U3kgJU4ZudcHHxepxa2+hibvZ4snig8NLOR0EGbmzcDWKWivN4HAI0Eo5yIvWkqjzpb59Drgy77whSXKg94yQ+Emin9AvBCvWRB8HFB5Zbs2mXIUZIco7vgszLgyYc89qeLFdCLfXMIxlHO9l8+HNXlVXFqOqdbZqg3bUeWnZIgR/xoPErDYjI4K9ugyLHAkb0fkg9IlCuhmP4tw3Qdxc3BFEY6vXm7aZ0+Dd8u8Uwej9qn77Gd2vwys1gHzJVqJ1692SK+RMj0KvW9j25EjCIyiEdZt5q9sPJDoFJA1Edl89MbrxTjx12XegAjOW+BG7YncRF78ZonidJ89DBTfw3QchI7k918u8Qf42iYWVCu5N3XK+40KkHgmOdYWcBb6qXGullHEGgp8lLhuZVkNjuTH86e0zX+k7q0h2FlRzS/mHyhZOyK/SmKrYSbHDggrhuNsnsGm/HbdeTE8Eyi2wjMaQ5iDSMF5wj5+cvx9gwoPtAaD4Dh3O3f6x90IDFwihZ+ZD+/IoGSiltm285wA5+UUFQeS+fwsnk1iqBNyaeWYCLz3defzD17Qwr75CsUNjdFSrqVUa/rn39hi374ABI5YectY/PaP7iYjAIEefgqBilYRnjxbGi+mjDiBqAPCg5s3UYIJmxEfH9xkJdl+LTxgcats9q3hAM5p/cei6dPeze7M3fqsH236YRr534NDvrTQdYjgQCDWWDbfZei7m795yrl/oNDEbi+CB/+aIZtpaQkF+x+pTl2MUMHQYzqkcb8jdvcT07U71U6xSvtOK/kGDzLkqfm3g67rkGXiht7o1U4FakSP7yH70MIU54HIEFjM/MX14EAQhCeKr6qow+hyi+A4pNB+TiPOVX5whRVp8fO7yNv+GXvy5JnjGinM1HjdvYwMeZq8SIEm9up3GIlYUa8TUVG/yGe0JzR+G3S774Svj3L1Gioscwc8+H+C0+MmrL4ywny6ZuAFl2VVFG+tPPS8lB/2PgE731/22khc9/1UfMUkOV8LDglpI9/zp148XRyq9hTfMcTr6E/fzFR3CxUZvJZ5/r7TQFiFWbWa0wnuKC9Jf9ge2fnfEttAhr8JWCSCAkrrgVrF5lPgpcv92hdqlfllbjKZ+BtA/+5dDB6b3Ja8YYwy7ICGTwHQiAELgHqAZqlq0q59b9+j2TLlZOrPVh2gqUwFEjMJbHIk7RmA5TGxBx5HgRfax+z3wVyWJ5B7XxXEZ+KvpRVyxykkduGvpWBJDGIX/K2p5h4j9Z5K7Ehuf4oBhPWqpIolDIMbEzUUocAym9i6/zVhY7o3JtqgVlHBkT0uYbs6H2hJ2VBhdGXKCxGgR7jICyM0UWqLOpVVPpgWq7K/S5JCxg6k1ujIGmxXRjJXJxqWEt0vtmc/3WMQpqRbo6aueHsOh0kDH+YMzO6JaUTo7CC/kLitBqsvN07fKR7XR1Mn/XTol7rI8jFmalyJ/YdhV3ylx/LRlaIekqL0inOZQa6eG7rv1Dk11EkwulUS+HjdBweSYflwNbGpYsJQbNnkYBE2AE5JrkA5M0Wx4rv9v3ZorgWaWQPbWQmErETBS8B7pDWCYptuuDZL1yJLteEwbFZIvzu6tg6RBFkOwAH2hnvfNBP/MMj5uW/VQ91SoQV4wWlAei9LPdtAoCxCxJSosOekG3iByMXiAYfB5SXKGxBdymo1MrPywZqAIA6XYSqpJFTbVJuPdpnXJMdVkm9XihZQJ+ov1ANK8md7jlBDzjyRKbaEZuHaj/GZGzvt1XMgfvfSq6BSqTbAc59ujvJBTqj8hFQ1+UAGfM+MpzTHG7e3bCSVQyRVZKOeTeeZgXsUQs6n0b9FvJh7RiL/x9YJxwRRX4qwl3+0D5PcioOryCv4oj5AwcIEXpUgB9+2oxsAo/Y5BGVFc3RBFXkcWdEpoxEppLwED2We4EzIi30d5KoeeSB5aXR/cVGIKqG7jKKv8tEaPP92afT/uk9kBBitYuDgshOqOWluarANl9B/E6Fto6xfWvEQQrb8Df4YfoDAioMh1M1RZjtv8zSo3PWQs6VE3cPS5dMqvr4EIplDgERTVcdZqtd1DCnfiqH/CkDSPLwu+CnHDJOk1lzM25qv/4a819z9ktRGVnMuruDezyPWWEDYvUZLoer2zFWOiYA2RSVBHmJqraZycCJuk3alwYS5CJEXKZjHCGKvFY1rCDJIkadfsTnpH4/KQQfoh0bha3nO59nkvrEBOw5UxQp26AmaNLmvH2uYIcxo3A+3+1d/DBQBMpWF59lMhZ9NV4VTnK4YxKKJXF1pEKMpSdpynbQfJphaR8wM+dd3PF7bM9qcGaQAdYV0/DAInHSPy/P1oz4UrUmrYFC8RIFp4uRNULw7WK7JAis4pOFGLKL6CJd9txJWCBUtKPD1AdGigyREAdubYXiBl0wV0FQgUHdjG1ehWQgCHTNn1yoO+OD8AKGUHte29tiUDWA0xbjLBbgkutJOSsBMNVC5qHzIqeiHx33SresonSPt6BDf4aO8ddBCh/T3aRO6l/j50Fd9s9OsKk4dioLopUeGr63Z}"
              scope: GLOBAL
              username: "cccaternberg"
          - usernamePassword:
              description: "githubuserpw"
              id: "githubuserpw"
              password: "{AQAAABAAAAAQ98ll4qGPcM3nPFRdWByDDby1yPBye3f/yjFJM+IHgmA=}"
              scope: GLOBAL
              username: "cccaternberg"
          - usernamePassword:
              description: "githubuseraccesstoken"
              id: "githubuseraccesstoken"
              password: "{AQAAABAAAAAwh3gRZSwSh4a9pOvMkOthXy+6fWsw2BQvY2V+pamtbogd1XQ6vCLmX++jPIOkdweZsNFHsWqoctqUfFbgfeu6PQ==}"
              scope: GLOBAL
              username: "cccaternberg"
          - string:
              description: "githubaccesstoken"
              id: "githubaccesstoken"
              scope: GLOBAL
              secret: "{AQAAABAAAAAw655NYw03krf88IyOQTrgpZA4vVGj5ENmTOaV9122gSuJB53aOUl9LWgjwFLk7uoEYpFKOmyUciNYMjyF4EJElA==}"
          - string:
              description: "Webhook secret for https://github.com/apps/pipeline-demo-caternberg1"
              id: "63fcee06-74ca-4a3a-9138-043af8e0c8d4"
              scope: SYSTEM
              secret: "{AQAAABAAAAAwnFQOoB0K41UBHEG9OWpLJGmprJD1omewz4OOWOUZFJUjTfPZX7HM1BJIpMQq7WGlVoEveoVaSOs4FXje7cpRDA==}"
jenkins:
  systemMessage: "Jenkins configured using CasC v.134 - ${MASTER_DOMAIN}"
  agentProtocols:
    - "Diagnostic-Ping"
    - "JNLP4-connect"
    - "OperationsCenter2"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
    - name: "cb-core-maven"
    - name: "cloudbees-core"
    - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  projectNamingStrategy:
    pattern:
      description: "My naming strategy"
      forceExistingJobs: false
      namePattern: ".*"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm: "operationsCenter"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "virtual-cap-core-mm"
        url: "https://jenkins-updates.cloudbees.com/update-center/envelope-core-mm/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
jobs:
  - script: |
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }

      organizationFolder('GH-jenkinsci') {
          description('This contains branch source jobs for GH-jenkinsci GitHub')
          displayName('GH-jenkinsci')
          triggers {
            periodic(2400)
          }
          organizations {
            github {
              repoOwner("cccaternberg")
              apiUri("https://api.github.com")
              credentialsId('githubaccesstoken')
              traits {
                publicRepoPullRequestFilterTrait()
              }
            }
          }

          projectFactories {
            workflowMultiBranchProjectFactory {
              // Relative location within the checkout of your Pipeline script.
              scriptPath("Jenkinsfile")
            }
          }
        }
cloudbees-monitoring:
  conditionList:
    - individualHealthCheck:
        alertAfter: "5sec"
        name: "health check"
        recipientList:
          - email:
              emailAddresses: "acaternberg@cloudbees.com"
              subjectPrefix: "[Jenkins Alert]"
beekeeper:
  enabled: true
  securityWarnings:
    enabledForCore: true
    enabledForPlugins: true
  upgrades:
    autoDowngradePlugins: false
    autoUpgradePlugins: false
notificationConfiguration:
  enabled: false
kube:
  podTemplatesConfiguration:
    templates:
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "maven:3.3.9-jdk-8-alpine"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "maven"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "appropriate/curl"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "curl"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "gradle"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "gradle"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "lachlanevenson/k8s-kubectl:latest"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "kubectl"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "lachlanevenson/k8s-helm:latest"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "helm"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        instanceCap: 10
        instanceCapStr: "10"
        label: "cloudbees-core"
        name: "cloudbees-core"
        slaveConnectTimeout: 10000
        slaveConnectTimeoutStr: "10000"
        volumes:
          - persistentVolumeClaim:
              claimName: "maven-repo"
              mountPath: "/tmp/cache"
              readOnly: false
        yamlMergeStrategy: "override"
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "maven:3.3.9-jdk-8-alpine"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "maven"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        label: "cb-core-maven"
        name: "cb-core-maven"
        nodeUsageMode: NORMAL
        volumes:
          - hostPathVolume:
              hostPath: "/var/run/docker.sock"
              mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "benhall/dind-jenkins-agent"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "dind"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        name: "dind-podtemplate"
        volumes:
          - hostPathVolume:
              hostPath: "/var/run/docker.sock"
              mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
security:
  anonymizeSupportBundle:
    enabled: false
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
      - "method com.cloudbees.jenkins.plugins.sshcredentials.SSHUserPrivateKey getPrivateKey"
      - "method com.cloudbees.plugins.credentials.common.IdCredentials getId"
      - "method com.cloudbees.plugins.credentials.common.PasswordCredentials getPassword"
      - "method com.cloudbees.plugins.credentials.common.UsernameCredentials getUsername"
      - "method hudson.model.ItemGroup getAllItems java.lang.Class"
      - "method hudson.model.Job getLastBuild"
      - "method org.apache.maven.model.Model getGroupId"
      - "new com.cwctravel.hudson.plugins.extended_choice_parameter.ExtendedChoiceParameterDefinition\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String boolean boolean int java.lang.String java.lang.String"
      - "staticMethod com.cloudbees.plugins.credentials.CredentialsProvider lookupCredentials\
      \ java.lang.Class hudson.model.ItemGroup org.acegisecurity.Authentication java.util.List"
unclassified:
  alerter:
    conditionList:
      - individualHealthCheck:
          alertAfter: "5sec"
          name: "health check"
          recipientList:
            - email:
                emailAddresses: "acaternberg@cloudbees.com"
                subjectPrefix: "[Jenkins Alert]"
  ansiColorBuildWrapper:
    colorMaps:
      - black: "#000000"
        blackB: "#4C4C4C"
        blue: "#1E90FF"
        blueB: "#4682B4"
        cyan: "#00CDCD"
        cyanB: "#00FFFF"
        green: "#00CD00"
        greenB: "#00FF00"
        magenta: "#CD00CD"
        magentaB: "#FF00FF"
        name: "xterm"
        red: "#CD0000"
        redB: "#FF0000"
        white: "#E5E5E5"
        whiteB: "#FFFFFF"
        yellow: "#CDCD00"
        yellowB: "#FFFF00"
      - black: "#000000"
        blackB: "#555555"
        blue: "#0000AA"
        blueB: "#5555FF"
        cyan: "#00AAAA"
        cyanB: "#55FFFF"
        defaultBackground: 0
        defaultForeground: 7
        green: "#00AA00"
        greenB: "#55FF55"
        magenta: "#AA00AA"
        magentaB: "#FF55FF"
        name: "vga"
        red: "#AA0000"
        redB: "#FF5555"
        white: "#AAAAAA"
        whiteB: "#FFFFFF"
        yellow: "#AA5500"
        yellowB: "#FFFF55"
      - black: "black"
        blackB: "black"
        blue: "blue"
        blueB: "blue"
        cyan: "cyan"
        cyanB: "cyan"
        green: "green"
        greenB: "green"
        magenta: "magenta"
        magentaB: "magenta"
        name: "css"
        red: "red"
        redB: "red"
        white: "white"
        whiteB: "white"
        yellow: "yellow"
        yellowB: "yellow"
      - black: "#2E3436"
        blackB: "#2E3436"
        blue: "#3465A4"
        blueB: "#3465A4"
        cyan: "#06989A"
        cyanB: "#06989A"
        defaultBackground: 0
        defaultForeground: 7
        green: "#4E9A06"
        greenB: "#4E9A06"
        magenta: "#75507B"
        magentaB: "#75507B"
        name: "gnome-terminal"
        red: "#CC0000"
        redB: "#CC0000"
        white: "#D3D7CF"
        whiteB: "#D3D7CF"
        yellow: "#C4A000"
        yellowB: "#C4A000"
  artifactManager:
    artifactManagerFactories:
      - "jSync"
  artifactoryBuilder:
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        ignoreCredentialPluginDisabled: true
        overridingCredentials: false
        password: "{AQAAABAAAAAQGj2K9LC6b4aG7PKev4UKyL28qfit1+WC/cvLTAM2Tys=}"
        username: "****"
      timeout: 300
    useCredentialsPlugin: false
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketCloudEndpoint:
          enableCache: false
          manageHooks: false
          repositoriesCacheDuration: 0
          teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  cloudbeesPlatform:
    server:
      apiUrl: "https://flow-server.cloudbees-core:8443/"
      ignoreSslConnectionErrors: true
    url: "https://cb-core.caternberg.eu/"
  defaultFolderConfiguration:
    healthMetrics:
      - jobStatusHealthMetric:
          countVirginJobs: false
          failure: true
          success: true
          unbuilt: true
          unstable: true
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpPassword: "{AQAAABAAAAAQO/3oDJYbr4OjQbCZk4Vnb9n/CbqxfIc8QElrxyVj6G4=}"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  experimentalPlugins:
    enabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "https://cb-core.caternberg.eu/${MASTER_DOMAIN}/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalNexusConfiguration:
    instanceId: "92096b7097d844359862c708e6812108"
    nxrmConfigs:
      - nxrm3Configuration:
          displayName: "mynexus"
          id: "nexus"
          internalId: "6a31d43f-3033-4419-affe-b9566836fe47"
          serverUrl: "http://nexus.34.98.108.14.nip.io/"
  hashicorpVault:
    configuration:
      engineVersion: 2
      timeout: 60
  hibernationConfiguration:
    activities:
      - "build"
      - "web"
    enabled: false
    gracePeriod: 120
  ivyBuildTrigger:
    extendedVersionMatching: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://cb-core.caternberg.eu/${MASTER_DOMAIN}/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  usageStatisticsCloudBees:
    usageStatisticsCollected: true
tool:
  cloudbeesPluginUsageAnalyzer:
    enabled: true
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"