credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              description: "githubuserssh"
              id: "githubuserssh"
              privateKeySource:
                directEntry:
                  privateKey: "{AQAAABAAABEQDbB5C/uqyn9OzsvnTP2T4jIjiBMW6DTLDYhJspkFf/dKRQ52Zd98t5LS6Gl3kJXiCEQAMg4xc9E2gHRj0FfNlXsSZjE5t1fdMPXczMDanN51b75wrri2Cw2qh+FdOLTGHYnGFYdMJgrxHWMedXHhACmoYyvA/a/dS+Np2FvbjLaXsOGTZPYcN6+tgGnJRZWlAPsa6YRWH+DF7ebgm02qOCkZdPgh+6Q2dY2/j/rGuyaolFOw+fN8ZuqsoPjv4r0LaovUIv8+MNarzZKPELRyxG7/vg/Wc7rdSfalbnUI2WnRpah3TH26be79ri5K/VJOpfgzGsadQGVaiW4PnftcEn4zZP/Q02K+c6gj0zjpI8H5bucE7KTYf0yTHmz8FQKdjYZX87SpZ52UE+tSbNwic3my506h6+Zs86nG3dsyar/14Fi6SG7bTfD7mr9V0tcv4NChceqySFch0eIgziLSKfLCUlSTbDeRZw2cYISh4dSGzVbDqVKPkMe1GIEw3XWOm60+Li+QDtGvaECes1qw9FhGStWDtmkv629I8Of0Xnnetsg7qcfTeFouq8JCikSNb3FHFCJQyKPQAba8/uAbum5ulvJTJsBaAs6b/WICU8js/93Amdfp7IoGHZOCAEInzoVkMdAQ4/ppnAgyXEjBAVBkjSHuipKh2zedp/a1lJH1SXoQUWTAwjpc8BKPf+F6Z+LkB3oEBJJ/4X71+Wy0xFKpJnCSPEe//Na021EMfYIxPn5UkG1NLdYon7qAABAd6jCRim069qYMLv1JrRuLiny24Df873bjK3f0d1kblCmQi7R3JKppBd8iayMQbMe+8n8p8WuIap399GKvmo6F+QPLkycCkv5sc8j3gVLKJAxroJF7l+HkYF7qXSZsgtUh67Wqutq8C+KGXyGKakBNjjlLKyd5UF+//0iHGgEK+3Jh4d39rMyIn5sVqd2uLeaIkh+rri9g9chIYq/DfKFHFE6aMC1eNzNab8F+ruYKkgOsRLLZQhsmd1GzE0Qbyqa1lZ+67FELT5SiRwAdZ9OuezpJerpikj+W+GY8HfKpNO2wnX7t3ojZJadaJ8BA0dDGXFYWUNwY0ZM/5lSR+fZV50r341FBgUNNNcAIe8lUDEZN4X8xjLrR07T6fr8oBbk+GkIMv6fpcibSOUjyKgZU6dvPmdMEHCZov9/aIkFg6DhRvDjq7oqUxE2iMFkSI5ymN9DhHleCgN8VDOC7SG9Leh6pFHiDLLWM6MmYXBdVWQhfjZIm8pkyWxjWxDAqzZ8AGzApp5nZ85KLgUpfwAkKaRcIQmsvbBsDQ95UYyp+vIWTKWBy4gJGHYFdrymZ3uzlirGepKXtlmODFWAQ+ogOMWm+F5yLJC4PT06G2Hv6bnxC3YYaLpIaB0Tb3EkgI/dhLWgrbVEjiMVbNCoJ+OjiEWOY3iogRk4ceeK818c+hvCwouJBdSMF7Jnwt3q677/MX2yJtjj8e3STsPOUPjYeCw7JHfQB8uiq9KvwB7rw6bfp/VbOKXXaQ8+U85ubCk4Qh2vNBSfMXUpGtsoiIxSGXXFNxtCgFxSyth5bLKJM6343P3JMKlZrk1n/8UOiw5jT+RRxHE7BPt4NWluPu3CBXELsKwR40X9iKgg4LFf2hyM3VuOc78Fqrzh9UF7vAr1LJT5Z4dX/yS9F0KZsSWRyYkdy9UgbVrKeRaLufpaZ/RZ+qHIGLjo95sRRc1IiPSpHzNhBD/nz6X/NO9QHgJHEDopbSJjHRXOro1yB+ZhLc0BsnUxki3kTBP0Ydr9Ijjz7PajhwOP6AOE18/X0pEEW+AZX2k4aIA38bM4nG5DK48LScOKJL9pUweg3T3t8wjkdc9XG18u4MJkD1sgLoJodu4Ch4CydPalRwZKW9OjmvFdzl8uEbMLfUIw0OYGx2PSS/FgC7/J5ETzYU3PjiZ+rL0rcm1zGFJCqwCX+Q/ZbDalEDWYLbrqQ6fjskG7VcZA8666HBPfI1uI5pf6IohFAJuz0knQwjlXQPRxN7IQlh1xNEIU4mK+4yML5XbC/Pu2mzSkOk2BMBzekuNAr7O0tlQt9+bkxCvgVzKw4MusdC/e7gtgpkevi/xgdejZDmOqg7GsOxFsKCoBC8GWu11uvce11+OcHKwQKRj8SItgVS7irGDu4cgo1WNGkrFId7yTW5cE0hxrcL+3ATW7XxVqxglo3Nu03PijmAmQKJP8+g6FoslX66C74lqqwcqLt6lzXPj8VMvHBIuTc8/xOE1rDb5S9iAdOc33MZ0mI+rvB98zL5ODJBZXUhjuFAFV1Q1x2S0YbnnlXmVeiXdyIi6kVAEkrK0Lyb1Qtyo7QSmqw2gKlb34zOR6RZtEE6ZR82ex3wzVCoso43Mq8ONE9YQukID8MBBjNfiPYZmNIuNKsRqYlzBM3EF5MiIP6A4wiL23M+T4gthOm9k4pnosCn2MUjgjJAVRazIOzU3345ULUJYj7AodE3njzXIbwxX4b3g3nXvFJA8ZVZSdU3vikBUvW1fKr+OGSjiCaBQD3vGBRJYwHQr4akAWID7kai5U+ubde5EPSq3mvQ+T/tK9lyx4oi1ZZM+FV+F/n8zM0WuX1XtMMJDrnyK1wSpHfRq8Og+EifUn6FfzmzWEAcxDErI2KRSV38kzH60DLuz+0fXSPEhcxPi1Z6D0FPyPEe0PnkJ777DskmxbSW00H4jXPZ2qhvmo8hQcQnfiGVqjeM8ZZ7rUFJfys6Yry9ReWGWnOZoQsbQrOdi46Ht0dvsn4iKVq1UIJqst0AvKsCUFDpxvK2UvkDUpVlrZFj2fRM/Ml3IvU+xUpSI7N1nL5cVhazKY2He5y1+za7acvFOrZYx4/9caDDXrybigVvahqC/orQ9sCmvjAJQl/MNNLL3uTTHvfiresSicQBejbVzIefipcmdop8aQ8b+FWlMGzJ5kN3+FtkpSv5zqRr7GRufc9IdC4eOkm6Vj7dsQYfV0DUfOAFOIBb54miWC9SWw4tfGRqNfAj1YbOf91IksUR9S4XJwa5s276YqN7Xfm3kJuBG9qD7vWiDaTH8a4Q8gcnbd30WQi4vXS5hB2HNuvKrIfDKEEXO6wP73xgs0jOs50AqFgF00L62oEq+L/V1ez53ut7NpoRoOFjUjehGkGPVvb5Eb85Ba/Qd5zZThuVVjRvDQb7xsofNEEctv6Re+F+U6AIi+AUZl0tuuTRzP1OUmS3ts9KoO+srzIsogmyTaYMHlpBrjjl49tjFcc5py/aIxXo7cHMGvgFUFS4Ifr3cK1eY2acgpG7opdGj48oHkQuYJEZRrm2iClbFjW9vy0AT0gSJSwZrm0DXuPdSDXF2aVa+rkInNRPtv4gcI0yFHPby81F1E3JWUu1k1gURpVnZ4JcySHDCvXvubx3Pf1lqtCUZjbgNN9z+SFgK/dZ87KRxNaVkAjBmn3m5V1mli2mBFRP96DRzfNgV5072ssoL/2pfnJPC7kTnTQTDUF2KiqWiU5Q4pVs5Bl0FyL4bipm3QefIJ1PpYe42I+cBA4VubhoTRX7ZWUQIw46RBICHZqLwsosPQnzKxrwvXwn3CDfF1pVCUxisgRvBFpRXTQclSF9bq0he7RNWRDNW+O02qE/9uLtFs3TP3jzAq2VfK2NuE4n968ACnREZREA1QNTK5czt5ufoVAvGahiUPVK0/r1vVM4oCZJaJ+J8W/o2asCBOtOnxWuhGz2yQKqbbujbbSnHjWUAXZb0NQ2ag3/X8zhIArktTtNdiYUw6ssKw4GtCb4683QihmuwKwdlrU6nd7ebbJI/kIKBJ2tVhv4IrXH3YMttcEVxSgzlWysluUKKhTtI+4Ojc4KYorPHOjnjIx0x/P7j2eDKffcIlz2F1WPkygWi1Ar5UwW/3wcpo6cyc2UVqA4w7DNgA4qv9iLYcLe9rYO2ish/9kVKRd/T9gQ7JTfXppmjq+IANxgOMj6cA1mJNNCPJ/mPeRvk6FKil1MQyooDI8i3vqQrgFEq6goqcKm2UYg6qQ+d/cg0FKNRdDw8GQJI4wqJMB0Qwo0NXn0eG82t6gng4BKUsSAafUD/Zz/gwjzZtNNGi96/4YXx1RHjQyAjj7p6F+7/DtX9ItjrVYT0KpPBne9E6tiW0emBzUAuGTEWLJf3HwVBfhBeCcmj5R5XqFqJi5C74Zfc8BTWLJ/BPhP+e1LCQsnVjhdtSUb3DkwO0xc17yQP86v57EmW16C/A/9y2sdbYPE9ithNDah6Dl02A5T56QHFm/X/5iMoQEk7es+Sag4ggRdZ0Q0aMNjXu0VcluTqJb65wN/Z8cgFPi8fZF9H/JfTEcw2Ia7U+IOiqE45MT1X1+Pp+vt6pO40/y6DDJNMHX8Va4qqkkNMtp6XyqZzhZurCKAL9ReGCCLPd0kbDfx1AjYtfczZjB98jDBnklP1pAapEfmHkSHtkoLUYcJpdhLl6eJs6i4nJC5QxBH2/cxyxmxyg0850rZ2bbo1xinDVYF5RgDXO3yYMu+rm421gURatYlXCScqe8RIhz8WL2KgmvOzBPV4vLGWIx78u5/cMFhGxYy0QSZDa8iyUpTMWxVdz2EzMCAffkmEHSBLdlnJKxgXxFkbO9qb2exXNdA0rPiwvFhlRmn232RyDS2InvbL3+SQ7b6yN2c5stp9ElnOSFHGgD1HxEGA+A5retkNMgaJIq6X7JRFvssrHz1hx6Lf+Co7CgNsejdpTPlbgLGzc/enIqSx37woU5Tg+jwJjLgcb8HbBEvOx2rckOqkDVEbQ5ANnCWuKckk8pG9k9yTi2V17/ykv/FIkxSm29yxVtpGMxDMnPfAi9658BlrXBCBTGu6z6sdEoFOWvn6+2n2EJcq4DymhXjdgXdCb/rMyuA8R4BQKkVTpXZo2ROVRh+CkI/FA7i+z4kEAfhylCf5toVTXrt1hR2sLR42VnMKXu1oDOnfIvvB9XCuOYSQ3gXmelVr8LkliuabXejQ+u0yyEy1ye/SnU1ypbPfXCu0+htudSkG72JmqrGH4Bq0Kml6MjtjMl2OgmJIYNKvu5IvRFkAWtXKI6vVOAO6nubS+qPRL1YqJYqYG1OJaBaLv2WMJKkRIfwAVLWiW/QWrt2qO0/3wEqpQFYQ2zxPh8v9JHoZ/noUslFgKmaDO+FGjL53irVnkUbn7+Xu1aOtIOugg0CLii3RSjeebBGn5Yoxfsj2qeegxzBHMiaOdZ18gTD6R7bd8q7yhp1vb0XoVr/fB4IVKyos6PuqTxS6YbNuLzOGiUuYBmWhSfI00ZNVEy1tijVu/YSg3p9q86sFLhSqx9XIkSnmMSvhBpyNTGGCn9G8k7cCkvZRzJXAnvdtwvxITAQ7L5JtB7VebmHQkdX22z8HNwW9IReDfXBj+KQ+fTH6tQquDMEtokvZ/QDEdj7mm/ReFxNS5DvXSqjK8FFrDzDqB0m68bh1UGP7VoJ0liKH3Qn1OEwCw6rEaI8GD9n/f0G5x/zpCo05AwflX9NxZUV68idMwP6IZ650Qe2fflwYDsLGYuYBxmZhGwvTKs8sOju0IMMI0LwG76/EJAeI/slixQSi6Wk64bzkxyilK4QllQclu9KlDpjYRXEefgMN0wcl1eE38stoQ80hN//8xImAHU2cMR+jebbWfJ1xWBKLES5kXAe02mk68sxTHHXHt6CI8ZfPec1nCVoacOBHG8ZDwJYDQtUyfZltfQPJoY8jhyy/oro4vb8TEGxEABw4jA2ThwEHZA4Pgf+Lkr7bRe53cfFXiG2pe3pFd5tmzUAw3GAkK3sFDqm0Bcsx+RA9Z4zs0rhJtNJEhUrFvBVyOPgm6Pttv5JLROXvR6QZBiKlP05t0NOA==}"
              scope: GLOBAL
              username: "cccaternberg"
          - usernamePassword:
              description: "githubuserpw"
              id: "githubuserpw"
              password: "{AQAAABAAAABA1UNwBi+HZE9mO1cRNF6RUgS+XjC4OpcdhcH+zwgQR1iJ4AZt79Iu76MFgqPO05d70IjZwcQPVBuKDX5tpLQ6dq9K4SxEHCW3RgoFIRrosjA=}"
              scope: GLOBAL
              username: "cccaternberg"
          - usernamePassword:
              description: "githubuseraccesstoken"
              id: "githubuseraccesstoken"
              password: "{AQAAABAAAABwaVTwFLCXmEgpC8Xujjy81HLFKQYEopuuqHk56L7hPMEQNN3NwSVMa9IWQq/l87p4XyOlx+ABXsQ1vvCNk0eHjcE1m5a50lpkeUbrlW0DK/5yIti1fMmzHse5sQa4vtZs4Y65LKPa+ndowJ98VPedqE5QEcKoclVvFfH97y2h8iY=}"
              scope: GLOBAL
              username: "cccaternberg"
          - string:
              description: "githubaccesstoken"
              id: "githubaccesstoken"
              scope: GLOBAL
              secret: "{AQAAABAAAABwy+JlMuRBsTgnqKU1rfoaaPhWwSSgkvVrKdC5aLUtiivCyKcjg2yLVXemcgi3MJ1pf/R0Iq8d30X+285iRjyNdzjkBVduuukZ8y8obxYOlDoO+2hJ/Bp9y7A8xPFUSv96di1dJW9qKLWccPbpLbgz7X1AMyP+6cQ4n08seCciTWw=}"
jenkins:
  systemMessage: "Jenkins configured using CasC v.107 - ${MASTER_DOMAIN}"
  agentProtocols:
    - "Diagnostic-Ping"
    - "JNLP4-connect"
    - "OperationsCenter2"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
    - name: "cb-core-maven"
    - name: "cloudbees-core"
    - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  projectNamingStrategy:
    pattern:
      description: "My naming strategy"
      forceExistingJobs: false
      namePattern: ".*"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm: "operationsCenter"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "virtual-cap-core-mm"
        url: "https://jenkins-updates.cloudbees.com/update-center/envelope-core-mm/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
jobs:
  - script: |
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }

      organizationFolder('GH-jenkinsci') {
          description('This contains branch source jobs for GH-jenkinsci GitHub')
          displayName('GH-jenkinsci')
          triggers {
            periodic(2400)
          }
          organizations {
            github {
              repoOwner("cccaternberg")
              apiUri("https://api.github.com")
              credentialsId('githubaccesstoken')
              traits {
                publicRepoPullRequestFilterTrait()
              }
            }
          }

          projectFactories {
            workflowMultiBranchProjectFactory {
              // Relative location within the checkout of your Pipeline script.
              scriptPath("Jenkinsfile")
            }
          }
        }
cloudbees-monitoring:
  conditionList:
    - individualHealthCheck:
        alertAfter: "5sec"
        name: "health check"
        recipientList:
          - email:
              emailAddresses: "acaternberg@cloudbees.com"
              subjectPrefix: "[Jenkins Alert]"
beekeeper:
  enabled: true
  securityWarnings:
    enabledForCore: true
    enabledForPlugins: true
  upgrades:
    autoDowngradePlugins: false
    autoUpgradePlugins: false
notificationConfiguration:
  enabled: false
kube:
  podTemplatesConfiguration:
    templates:
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "maven:3.3.9-jdk-8-alpine"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "maven"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "appropriate/curl"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "curl"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "gradle"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "gradle"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "lachlanevenson/k8s-kubectl:latest"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "kubectl"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          - args: "cat"
            command: "/bin/sh -c"
            image: "lachlanevenson/k8s-helm:latest"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "helm"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        instanceCap: 10
        instanceCapStr: "10"
        label: "cloudbees-core"
        name: "cloudbees-core"
        slaveConnectTimeout: 10000
        slaveConnectTimeoutStr: "10000"
        volumes:
          - persistentVolumeClaim:
              claimName: "maven-repo"
              mountPath: "/tmp/cache"
              readOnly: false
        yamlMergeStrategy: "override"
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "maven:3.3.9-jdk-8-alpine"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "maven"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        label: "cb-core-maven"
        name: "cb-core-maven"
        nodeUsageMode: NORMAL
        volumes:
          - hostPathVolume:
              hostPath: "/var/run/docker.sock"
              mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
          - args: "cat"
            command: "/bin/sh -c"
            image: "benhall/dind-jenkins-agent"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "dind"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
        hostNetwork: false
        name: "dind-podtemplate"
        volumes:
          - hostPathVolume:
              hostPath: "/var/run/docker.sock"
              mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
security:
  anonymizeSupportBundle:
    enabled: false
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
      - "method com.cloudbees.jenkins.plugins.sshcredentials.SSHUserPrivateKey getPrivateKey"
      - "method com.cloudbees.plugins.credentials.common.IdCredentials getId"
      - "method com.cloudbees.plugins.credentials.common.PasswordCredentials getPassword"
      - "method com.cloudbees.plugins.credentials.common.UsernameCredentials getUsername"
      - "method hudson.model.ItemGroup getAllItems java.lang.Class"
      - "method hudson.model.Job getLastBuild"
      - "method org.apache.maven.model.Model getGroupId"
      - "new com.cwctravel.hudson.plugins.extended_choice_parameter.ExtendedChoiceParameterDefinition\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String java.lang.String java.lang.String java.lang.String java.lang.String\
      \ java.lang.String boolean boolean int java.lang.String java.lang.String"
      - "staticMethod com.cloudbees.plugins.credentials.CredentialsProvider lookupCredentials\
      \ java.lang.Class hudson.model.ItemGroup org.acegisecurity.Authentication java.util.List"
unclassified:
  alerter:
    conditionList:
      - individualHealthCheck:
          alertAfter: "5sec"
          name: "health check"
          recipientList:
            - email:
                emailAddresses: "acaternberg@cloudbees.com"
                subjectPrefix: "[Jenkins Alert]"
  artifactManager:
    artifactManagerFactories:
      - "jSync"
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketCloudEndpoint:
          enableCache: false
          manageHooks: false
          repositoriesCacheDuration: 0
          teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  experimentalPlugins:
    enabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "https://cb-core.caternberg.eu/${MASTER_DOMAIN}/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  hibernationConfiguration:
    activities:
      - "build"
      - "web"
    enabled: false
    gracePeriod: 120
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://cb-core.caternberg.eu/${MASTER_DOMAIN}/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  usageStatisticsCloudBees:
    usageStatisticsCollected: true
tool:
  cloudbeesPluginUsageAnalyzer:
    enabled: true
  git:
    installations:
      - home: "git"
        name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"